OutFileName: Simulation/Tree.root
NEvents: 50000

#Multiplicity settings
MultType: kCustom               #Possibilities: kConst, kCustom, kUniform
MultConst: 100                  #only if kConst
MultFile: Simulation/Multi_ALICE.root
MultHisto: Table 3/Hist1D_y1
MultRange: [5,100]              #used for kUniform and kCustom

#Vertex dispersion settings
SigmaZ: 5.3    #cm
SigmaX: 0.01   #cm
SigmaY: 0.01   #cm

#Material budgets settings
IsDetector: [False,True,True]
Radii: [3.,4.,7.]                 #cm
Thickness: [0.08,0.02,0.02]       #cm
Lenght: [27.,27.,27.]             #cm
Material: [Be, Si, Si]            #Be or Si
DoMultScattering: True
#Detectors only
DoSmearing: True
DoNoise: True
MeanNoise: 10

Verbose: True