NEvents: 1

#Multiplicity settings
MultType: kConst               #Possibilities: kConst, kCustom, kUniform
MultConst: 10                   #only if kConst
MultFile: Multi_ALICE.root
MultHisto: Table 3/Hist1D_y1
MultRange: [30,40]              #used for kUniform and kCustom

#Vertex dispersion settings
SigmaZ: 5.3    #cm
SigmaX: 0.01   #cm
SigmaY: 0.01   #cm

#Material budgets settings
IsDetector: [False,True,True]
Radii: [3.,4.,7.]                 #cm
Thickness: [0.08,0.02,0.02]       #cm
Lenght: [27.,27.,27.]             #cm
Material: ["Be", "Si", "Si"]